version: '3'
services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: thiio_laravel_app
    ports:
      - "9000:9000"
    working_dir: /var/www/
    volumes:
      - ./:/var/www    
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: thiio_laravel_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/      
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'mysql:latest'
    container_name: thiio_laravel_mysql
    environment:
      MYSQL_DATABASE: thiio_DB
      MYSQL_ROOT_PASSWORD: secret_thiio    
    volumes:
      - ./:/var/www